name: Deploy Docs to GitHub Pages

on:
  workflow_dispatch:
  release:
    types: [created]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          cache: npm
          cache-dependency-path: "./docs/pnpm-lock.yaml"

      - name: Install pnpm
        run: npm i -g pnpm --no-fund

      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
            path: ./docs # The root location of your Astro project inside the repository. (optional)
            node-version: 24 # The specific version of Node that should be used to build your site. Defaults to 16. (optional)
            package-manager: pnpm # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)


      # - name: Setup Pages
      #   uses: actions/configure-pages@v6.0.0

      # - name: Install dependencies
      #   working-directory: ./docs
      #   run: pnpm i --ignore-scripts

      # - name: Approve scripts
      #   working-directory: ./docs
      #   run: pnpm approve-builds

      # - name: Build
      #   working-directory: ./docs
      #   run: pnpm build

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v5.0.0
      #   with:
      #     path: docs/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
