name: Publish Packages

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # The OIDC ID token is used for authentication with JSR.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.x

      - name: Publish core
        working-directory: ./packages/core
        run: deno publish --allow-slow-types
